import { MaterialCommunityIcons as GlyphIcons } from "@expo/vector-icons";
import {
  Activity,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  ArrowUpRight,
  BarChart3,
  Bell,
  Bot,
  Briefcase,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Circle,
  CircleCheck,
  CircleDot,
  Clock3,
  Copy,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Folder,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  KeyRound,
  Lightbulb,
  ListFilter,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Palette,
  Pencil,
  PiggyBank,
  PieChart,
  Plus,
  ReceiptText,
  RotateCcw,
  Save,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Tag,
  Target,
  Trash2,
  TriangleAlert,
  TrendingUp,
  Trophy,
  Utensils,
  UserRound,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react-native";
import type { ComponentProps } from "react";

type IconName = keyof typeof GlyphIcons.glyphMap;
type NativeIconProps = Pick<ComponentProps<typeof GlyphIcons>, "name" | "size" | "color">;

const lucideIcons: Partial<Record<IconName, LucideIcon>> = {
  "account-outline": UserRound,
  "alert-circle": CircleAlert,
  "alert-circle-outline": CircleAlert,
  "alert-outline": TriangleAlert,
  "arrow-down": ArrowDownToLine,
  "arrow-down-bold": ArrowDown,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-top-right": ArrowUpRight,
  "arrow-up": ArrowUpFromLine,
  "arrow-up-bold": ArrowUp,
  "backup-restore": RotateCcw,
  "bell-outline": Bell,
  "briefcase-outline": Briefcase,
  "bullseye": Target,
  "bullseye-arrow": Target,
  "car-outline": Car,
  "cash-multiple": Wallet,
  "cash-minus": ArrowUp,
  "cash-plus": ArrowDown,
  "chart-bar": BarChart3,
  "chart-donut": PieChart,
  "chart-line": Activity,
  "check": Check,
  "check-all": CheckCheck,
  "check-circle": CircleCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "close": X,
  "cog-outline": Settings,
  "content-copy": Copy,
  "close-circle": CircleAlert,
  "creation": Sparkles,
  "creation-outline": Sparkles,
  "delete-outline": Trash2,
  "dumbbell": Dumbbell,
  "email-outline": Mail,
  "eye-off-outline": EyeOff,
  "eye-outline": Eye,
  "file-chart-outline": FileText,
  "filter-variant": ListFilter,
  "folder-outline": Folder,
  "gamepad-variant-outline": Gamepad2,
  "gift-outline": Gift,
  "heart-pulse": HeartPulse,
  "home-outline": Home,
  "key-outline": KeyRound,
  "lightbulb-outline": Lightbulb,
  "lock-outline": LockKeyhole,
  "logout": LogOut,
  "logout-variant": LogOut,
  "magnify": Search,
  "menu": Menu,
  "pencil-outline": Pencil,
  "piggy-bank-outline": PiggyBank,
  "plus": Plus,
  "progress-clock": Clock3,
  "palette-outline": Palette,
  "receipt-text-outline": ReceiptText,
  "robot-outline": Bot,
  "content-save-outline": Save,
  "school-outline": GraduationCap,
  "shield-check-outline": ShieldCheck,
  "shopping-outline": ShoppingBag,
  "silverware-fork-knife": Utensils,
  "tag-outline": Tag,
  "radiobox-blank": Circle,
  "radiobox-marked": CircleDot,
  "trophy-outline": Trophy,
  "trending-up": TrendingUp,
  "wallet-outline": Wallet,
  "swap-horizontal": ArrowLeftRight,
  "swap-vertical": ArrowLeftRight,
};

// Unmapped saved or user-selected glyphs keep their original Material icon.
function NativeIcon({ name, size = 24, color = "#000000" }: NativeIconProps) {
  const LucideIcon = lucideIcons[name];
  if (LucideIcon) {
    return <LucideIcon size={size} color={color} strokeWidth={2} />;
  }

  return <GlyphIcons name={name} size={size} color={color} />;
}

export const MaterialCommunityIcons = Object.assign(NativeIcon, {
  glyphMap: GlyphIcons.glyphMap,
});

export const MaterialCommunityGlyphIcons = GlyphIcons;
